### ISSUE TITLE
npm ERR! gyp: Undefined variable android_ndk_path in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by Freed-Wu** [nodejs/gyp-next#237]
`npm rebuild` in Android/termux meet this bug. However I cannot found `android_ndk_path` in gyp's code repo. How to solve it? TIA!

**Comment by cclauss** [comment]
Error log?

**Comment by Freed-Wu** [comment]
[2024-03-27T16_39_28_462Z-debug-0.log](https://github.com/nodejs/gyp-next/files/14776462/2024-03-27T16_39_28_462Z-debug-0.log)

It looks like node-gyp add some gypi contains this variable:

```sh
$ rg android_ndk_path /data/data/com.termux/files/home/.cache/node-gyp/21.6.2/include/node/common.gypi
241:            'cflags': [ '-fPIC', '-I<(android_ndk_path)/sources/android/cpufeatures' ],
```

**Comment by cclauss** [comment]
It looks like the alpha software crashed.  What happens when you remove that software from the build?
> 35 info run coc-rime@0.1.3-alpha install  node-gyp rebuild
36 info run coc-rime@0.1.3-alpha install { code: 1, signal: null }
37 timing command:rebuild Completed in 1514ms
38 verbose stack Error: command failed
38 verbose stack     at ChildProcess.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
38 verbose stack     at ChildProcess.emit (node:events:519:28)
38 verbose stack     at maybeClose (node:internal/child_process:1105:16)
38 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)

**Comment by cclauss** [comment]
Closing in favor of 
* tonyfettes/coc-rime#7

**Comment by Freed-Wu** [comment]
After <https://github.com/tonyfettes/coc-rime/commit/c91900b01ca84c1e43f53958dca30d3a59b23ab4>, it can be build in Android/termux. So can we add a default android_ndk_path to avoid this bug?

PS: It should be added in `node-gyp`'s `js` code?

**Comment by cclauss** [comment]
The error messages on tonyfettes/coc-rime#7  say nothing about `android_ndk_path`.  Let’s get that merged so that we have clear evidence of a `android_ndk_path` problem so that we can recruit other to fix that problem.

**Comment by Freed-Wu** [comment]
It's my fault. Let me explain the full steps:

1. Install <https://github.com/termux/termux-app> to an Android device
2.

```sh
git clone --depth=1 https://github.com/tonyfettes/coc-rime
cd coc-rime
# before https://github.com/tonyfettes/coc-rime/commit/c91900b01ca84c1e43f53958dca30d3a59b23ab4
git checkout f307fa8c71a042663111705e14611444cacc2955
yarn
npm rebuild
```

You will set that error message.
