### ISSUE TITLE
copy_cmd `cp -a` isn't supported on Solaris

### ISSUE THREAD

**Issue by cjbj** [nodejs/gyp-next#47]
The `cp` option `-a` in copy_cmd fails on Solaris.  Currently `npm install` of a binary add-on gives:

```
cp: illegal option -- a
Usage: cp [-f] [-i] [-p] [-@] [-/] f1 f2
       cp [-f] [-i] [-p] [-@] [-/] f1 ... fn d1
       cp -r|-R [-H|-L|-P] [-f] [-i] [-p] [-@] [-/] d1 ... dn-1 dn
```

A work around is to use `node-gyp configure`, edit build/Makefile and change the `cp` syntax to use `-pPR`.  Then run `node-gyp build`:

```
bash-4.4$ diff build/Makefile build/Makefile.bak
134c134
< cmd_copy = rm -rf "$@" && cp -pPR "$<" "$@"
---
> cmd_copy = rm -rf "$@" && cp -af "$<" "$@"
```

Also see https://github.com/nodejs/node-gyp/issues/562#issuecomment-620623044

* **Node Version**: 12.18.1
* **Platform**: solaris
* **Compiler**: gcc (GCC) 7.3.0
* **Module**: oracledb

**Comment by richardlau** [comment]
I've transferred this over to gyp-next.

**Comment by ryzokuken** [comment]
@cjbj interesting. I just glossed over https://docs.oracle.com/cd/E88353_01/html/E37839/cp-1.html and you're indeed correct, this is a bug. That said, I'm a little unconvinced if you can just simply replace `-a` with `-pP` since `-a` implies `--preserve=all` on Linux while `-p` would fail silently on Solaris for things like mode, xattrs and timestamps. But since Solaris doesn't seem to allow explicitly specifying `--preserve`, I suppose something like `-pP@/` should work better though, maybe just `-pP@`.

> maybe add an f too?

Right, we also need to keep the `-f` unless there's a good reason for dropping it?

**Comment by cjbj** [comment]
For background, I don't personally use Solaris and the `-pPR` options were given to me; they solved the immediate problem of the user who reported it.  I wouldn't expect them to cover all cases node-gyp was trying to solve.  I can see from https://github.com/nodejs/node-gyp/issues/562#issuecomment-620623044 that some node-gyp expertise is needed to make sure the final option choice is comprehensive.

**Comment by ryzokuken** [comment]
That said, I think `-pPR@/` should be as usable as it gets on Solaris, so as long as everyone agrees with this assessment, I could make a pull request making this change.

**Comment by cjbj** [comment]
It's definitely an improvement.  A PR would be great.

**Comment by ryzokuken** [comment]
@cjbj PTAL!
